package shared.requests;

public enum RequestType {
    DEFAULT,
    ADD_PERSON,
    CLEAR_PERSONS,
    GET_COLLECTION_INFO,
    GET_PERSONS,
    REMOVE_LOWER_PERSONS,
    REMOVE_PERSONS,
    UPDATE_PERSON,
    VALIDATE_PERSON_ARGS,
    SAVE_COLLECTION,
}
